#!/usr/bin/env python3
"""
Generate B1 and B2-C1 vocabulary for Quebec French Learning App
B1: 500 upper-intermediate words (ids 1001-1500)
B2-C1: 500 advanced words (ids 1501-2000)
"""

# B1 Level Vocabulary (500 words) - Upper Intermediate
b1_vocabulary = [
    # Professional & Work Vocabulary (1001-1050)
    { "id": 1001, "french": "l'employé", "english": "employee", "category": "work", "example": "Je suis employé dans cette entreprise.", "quebecNote": "" },
    { "id": 1002, "french": "l'employeur", "english": "employer", "category": "work", "example": "Mon employeur est généreux.", "quebecNote": "" },
    { "id": 1003, "french": "le collègue", "english": "colleague", "category": "work", "example": "C'est mon collègue de bureau.", "quebecNote": "" },
    { "id": 1004, "french": "le patron", "english": "boss", "category": "work", "example": "Le patron est en réunion.", "quebecNote": "" },
    { "id": 1005, "french": "le salaire", "english": "salary", "category": "work", "example": "Mon salaire est correct.", "quebecNote": "" },
    { "id": 1006, "french": "la paie", "english": "pay/paycheck", "category": "work", "example": "Je reçois ma paie vendredi.", "quebecNote": "QUEBEC - not 'salaire'" },
    { "id": 1007, "french": "l'augmentation", "english": "raise/increase", "category": "work", "example": "J'ai eu une augmentation!", "quebecNote": "" },
    { "id": 1008, "french": "la promotion", "english": "promotion", "category": "work", "example": "Il a eu une promotion.", "quebecNote": "" },
    { "id": 1009, "french": "embaucher", "english": "to hire", "category": "work", "example": "On embauche du personnel.", "quebecNote": "" },
    { "id": 1010, "french": "licencier", "english": "to fire/lay off", "category": "work", "example": "L'entreprise a licencié 50 personnes.", "quebecNote": "" },
    { "id": 1011, "french": "démissionner", "english": "to resign", "category": "work", "example": "J'ai démissionné hier.", "quebecNote": "" },
    { "id": 1012, "french": "la démission", "english": "resignation", "category": "work", "example": "J'ai remis ma démission.", "quebecNote": "" },
    { "id": 1013, "french": "le contrat", "english": "contract", "category": "work", "example": "Signe le contrat.", "quebecNote": "" },
    { "id": 1014, "french": "le syndicat", "english": "union", "category": "work", "example": "Je suis membre du syndicat.", "quebecNote": "Strong in Quebec" },
    { "id": 1015, "french": "la grève", "english": "strike", "category": "work", "example": "Les employés sont en grève.", "quebecNote": "" },
    { "id": 1016, "french": "l'horaire", "english": "schedule", "category": "work", "example": "Mon horaire change chaque semaine.", "quebecNote": "" },
    { "id": 1017, "french": "les heures supplémentaires", "english": "overtime", "category": "work", "example": "Je fais des heures supplémentaires.", "quebecNote": "" },
    { "id": 1018, "french": "le congé", "english": "leave/time off", "category": "work", "example": "Je prends un congé.", "quebecNote": "" },
    { "id": 1019, "french": "les vacances", "english": "vacation", "category": "work", "example": "Je pars en vacances.", "quebecNote": "" },
    { "id": 1020, "french": "le bureau", "english": "office", "category": "work", "example": "Je travaille au bureau.", "quebecNote": "" },
    { "id": 1021, "french": "la réunion", "english": "meeting", "category": "work", "example": "J'ai une réunion à 14h.", "quebecNote": "" },
    { "id": 1022, "french": "le projet", "english": "project", "category": "work", "example": "On travaille sur un projet.", "quebecNote": "" },
    { "id": 1023, "french": "la tâche", "english": "task", "category": "work", "example": "C'est une tâche difficile.", "quebecNote": "" },
    { "id": 1024, "french": "la responsabilité", "english": "responsibility", "category": "work", "example": "C'est ma responsabilité.", "quebecNote": "" },
    { "id": 1025, "french": "l'objectif", "english": "objective/goal", "category": "work", "example": "Notre objectif principal.", "quebecNote": "" },
    { "id": 1026, "french": "le délai", "english": "deadline", "category": "work", "example": "Le délai est demain.", "quebecNote": "" },
    { "id": 1027, "french": "respecter", "english": "to respect/meet (deadline)", "category": "work", "example": "Il faut respecter le délai.", "quebecNote": "" },
    { "id": 1028, "french": "la compétence", "english": "skill/competence", "category": "work", "example": "Il a les compétences nécessaires.", "quebecNote": "" },
    { "id": 1029, "french": "l'expérience", "english": "experience", "category": "work", "example": "J'ai 5 ans d'expérience.", "quebecNote": "" },
    { "id": 1030, "french": "la formation", "english": "training", "category": "work", "example": "Je suis en formation.", "quebecNote": "" },
    { "id": 1031, "french": "se former", "english": "to train oneself", "category": "work", "example": "Je me forme constamment.", "quebecNote": "" },
    { "id": 1032, "french": "perfectionner", "english": "to improve/perfect", "category": "work", "example": "Je perfectionne mes compétences.", "quebecNote": "" },
    { "id": 1033, "french": "le stage", "english": "internship", "category": "work", "example": "Je fais un stage.", "quebecNote": "" },
    { "id": 1034, "french": "le stagiaire", "english": "intern", "category": "work", "example": "C'est notre nouveau stagiaire.", "quebecNote": "" },
    { "id": 1035, "french": "la carrière", "english": "career", "category": "work", "example": "Une belle carrière.", "quebecNote": "" },
    { "id": 1036, "french": "l'ambition", "english": "ambition", "category": "work", "example": "Il a de l'ambition.", "quebecNote": "" },
    { "id": 1037, "french": "ambitieux", "english": "ambitious", "category": "personality", "example": "Elle est ambitieuse.", "quebecNote": "" },
    { "id": 1038, "french": "la candidature", "english": "application", "category": "work", "example": "J'ai envoyé ma candidature.", "quebecNote": "" },
    { "id": 1039, "french": "postuler", "english": "to apply for", "category": "work", "example": "Je postule pour ce poste.", "quebecNote": "" },
    { "id": 1040, "french": "l'entrevue", "english": "interview", "category": "work", "example": "J'ai une entrevue demain.", "quebecNote": "QUEBEC - not 'entretien'" },
    { "id": 1041, "french": "le curriculum vitae (CV)", "english": "resume/CV", "category": "work", "example": "Envoie ton CV.", "quebecNote": "" },
    { "id": 1042, "french": "la lettre de motivation", "english": "cover letter", "category": "work", "example": "Écris une lettre de motivation.", "quebecNote": "" },
    { "id": 1043, "french": "embaucher", "english": "to hire", "category": "work", "example": "Ils vont m'embaucher.", "quebecNote": "" },
    { "id": 1044, "french": "le poste", "english": "position/job", "category": "work", "example": "Un poste intéressant.", "quebecNote": "" },
    { "id": 1045, "french": "à temps plein", "english": "full-time", "category": "work", "example": "Un emploi à temps plein.", "quebecNote": "" },
    { "id": 1046, "french": "à temps partiel", "english": "part-time", "category": "work", "example": "Je travaille à temps partiel.", "quebecNote": "" },
    { "id": 1047, "french": "temporaire", "english": "temporary", "category": "work", "example": "Un contrat temporaire.", "quebecNote": "" },
    { "id": 1048, "french": "permanent", "english": "permanent", "category": "work", "example": "Un poste permanent.", "quebecNote": "" },
    { "id": 1049, "french": "l'entreprise", "english": "company/business", "category": "work", "example": "Une grande entreprise.", "quebecNote": "" },
    { "id": 1050, "french": "la compagnie", "english": "company", "category": "work", "example": "Je travaille pour cette compagnie.", "quebecNote": "QUEBEC - also 'entreprise'" },
    
    # Education & Learning (1051-1090)
    { "id": 1051, "french": "le cégep", "english": "college (Quebec)", "category": "education", "example": "Je vais au cégep.", "quebecNote": "QUEBEC SPECIFIC! Pre-university college" },
    { "id": 1052, "french": "l'université", "english": "university", "category": "education", "example": "J'étudie à l'université.", "quebecNote": "" },
    { "id": 1053, "french": "le baccalauréat", "english": "bachelor's degree", "category": "education", "example": "J'ai un baccalauréat en sciences.", "quebecNote": "In Quebec, university degree (not high school exam)" },
    { "id": 1054, "french": "la maîtrise", "english": "master's degree", "category": "education", "example": "Je fais une maîtrise.", "quebecNote": "" },
    { "id": 1055, "french": "le doctorat", "english": "PhD/doctorate", "category": "education", "example": "Il fait un doctorat.", "quebecNote": "" },
    { "id": 1056, "french": "la recherche", "english": "research", "category": "education", "example": "Je fais de la recherche.", "quebecNote": "" },
    { "id": 1057, "french": "la thèse", "english": "thesis", "category": "education", "example": "J'écris ma thèse.", "quebecNote": "" },
    { "id": 1058, "french": "le mémoire", "english": "dissertation/thesis", "category": "education", "example": "Mon mémoire de maîtrise.", "quebecNote": "" },
    { "id": 1059, "french": "la bourse", "english": "scholarship", "category": "education", "example": "J'ai reçu une bourse.", "quebecNote": "" },
    { "id": 1060, "french": "les frais de scolarité", "english": "tuition fees", "category": "education", "example": "Les frais de scolarité augmentent.", "quebecNote": "" },
    { "id": 1061, "french": "s'inscrire", "english": "to enroll/register", "category": "education", "example": "Je m'inscris au cours.", "quebecNote": "" },
    { "id": 1062, "french": "l'inscription", "english": "registration", "category": "education", "example": "L'inscription est ouverte.", "quebecNote": "" },
    { "id": 1063, "french": "la session", "english": "semester/session", "category": "education", "example": "La session d'automne.", "quebecNote": "QUEBEC - not 'semestre'" },
    { "id": 1064, "french": "le trimestre", "english": "quarter/trimester", "category": "education", "example": "Le premier trimestre.", "quebecNote": "" },
    { "id": 1065, "french": "le semestre", "english": "semester", "category": "education", "example": "Un semestre à l'étranger.", "quebecNote": "Less common in Quebec (use 'session')" },
    { "id": 1066, "french": "l'année scolaire", "english": "school year", "category": "education", "example": "L'année scolaire commence en septembre.", "quebecNote": "" },
    { "id": 1067, "french": "la rentrée", "english": "back to school", "category": "education", "example": "C'est bientôt la rentrée.", "quebecNote": "" },
    { "id": 1068, "french": "les vacances d'été", "english": "summer vacation", "category": "education", "example": "J'adore les vacances d'été!", "quebecNote": "" },
    { "id": 1069, "french": "la relâche", "english": "spring break (Quebec)", "category": "education", "example": "On part en voyage pendant la relâche.", "quebecNote": "QUEBEC SPECIFIC! Week off in March" },
    { "id": 1070, "french": "le congé", "english": "break/holiday", "category": "education", "example": "Un congé scolaire.", "quebecNote": "" },
    { "id": 1071, "french": "réviser", "english": "to revise/review", "category": "education", "example": "Je révise pour l'examen.", "quebecNote": "" },
    { "id": 1072, "french": "la révision", "english": "revision/review", "category": "education", "example": "C'est ma dernière révision.", "quebecNote": "" },
    { "id": 1073, "french": "mémoriser", "english": "to memorize", "category": "education", "example": "Je dois mémoriser ça.", "quebecNote": "" },
    { "id": 1074, "french": "comprendre", "english": "to understand", "category": "education", "example": "Je ne comprends pas.", "quebecNote": "" },
    { "id": 1075, "french": "la compréhension", "english": "understanding", "category": "education", "example": "Bonne compréhension!", "quebecNote": "" },
    { "id": 1076, "french": "expliquer", "english": "to explain", "category": "education", "example": "Peux-tu m'expliquer?", "quebecNote": "" },
    { "id": 1077, "french": "l'explication", "english": "explanation", "category": "education", "example": "Je veux une explication.", "quebecNote": "" },
    { "id": 1078, "french": "la connaissance", "english": "knowledge", "category": "education", "example": "Mes connaissances en français.", "quebecNote": "" },
    { "id": 1079, "french": "le savoir", "english": "knowledge", "category": "education", "example": "Le savoir est important.", "quebecNote": "" },
    { "id": 1080, "french": "savoir-faire", "english": "know-how/skills", "category": "education", "example": "Un bon savoir-faire.", "quebecNote": "" },
    { "id": 1081, "french": "apprendre par cœur", "english": "to learn by heart", "category": "education", "example": "Apprends ça par cœur.", "quebecNote": "" },
    { "id": 1082, "french": "se concentrer", "english": "to concentrate", "category": "education", "example": "Je dois me concentrer.", "quebecNote": "" },
    { "id": 1083, "french": "la concentration", "english": "concentration", "category": "education", "example": "J'ai perdu ma concentration.", "quebecNote": "" },
    { "id": 1084, "french": "distrait", "english": "distracted", "category": "education", "example": "Je suis distrait.", "quebecNote": "" },
    { "id": 1085, "french": "la distraction", "english": "distraction", "category": "education", "example": "Trop de distractions!", "quebecNote": "" },
    { "id": 1086, "french": "studieux", "english": "studious", "category": "personality", "example": "Un étudiant studieux.", "quebecNote": "" },
    { "id": 1087, "french": "appliqué", "english": "diligent", "category": "personality", "example": "Elle est très appliquée.", "quebecNote": "" },
    { "id": 1088, "french": "la faculté", "english": "faculty", "category": "education", "example": "La faculté de médecine.", "quebecNote": "" },
    { "id": 1089, "french": "le département", "english": "department", "category": "education", "example": "Le département de mathématiques.", "quebecNote": "" },
    { "id": 1090, "french": "la spécialisation", "english": "specialization", "category": "education", "example": "Ma spécialisation est l'informatique.", "quebecNote": "" },
]

# Continue generating more B1 vocabulary...
# (This is getting long, so I'll create the complete structure and use a more efficient approach)

print("Generating B1 and B2-C1 vocabulary...")
print(f"B1 vocabulary generated: {len(b1_vocabulary)} words so far")
print("Note: Due to length constraints, I'll generate the rest programmatically")
